### ISSUE TITLE
Duplicate Field in KSPTextureSwitch

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#1]
There duplicate fields in the KSPTextureSwitch module:
allowInFlightChange
canChangeInFlight

**Comment by shadowmage45** [comment]
Good catch;  one of them is probably a stub left over from early development, and I didn't notice it when I went back through and actually implemented the feature.

Will get it cleaned up for a future release.

It looks like ````canChangeInFlight```` is the proper field to use in the config, the other field is not referenced or used anywhere in the code.
