### ISSUE TITLE
Support for Float-Based Metallic/Smoothness

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#11]
On the SSTU/PBR/Metallic shader, could you add two properties '_Metallic' and '_Smoothness' as floats that default to 1.0 and are used as multiplier to the _MetallicGlossMap?

This would allow us to just use the default "white" _MetallicGlossMap alongside setting a specific metallicy and smoothness without needing to provide and load a single 1x1 pixel texture.

Example:

TEXTURE // gold
{
	shader = SSTU/PBR/Metallic
	texture = _MainTex,

	PROPERTY
	{
		name = _Color
		color = 1.0,0.84,0.0
	}
	PROPERTY
	{
		name = _Metallic
		float = 0.8
	}
	PROPERTY
	{
		name = _Smoothness
		float = 0.9
	}
}
TEXTURE // silver
{
	shader = SSTU/PBR/Metallic
	texture = _MainTex,

	PROPERTY
	{
		name = _Color
		color = 0.75,0.75,0.75
	}
	PROPERTY
	{
		name = _Metallic
		float = 0.8
	}
	PROPERTY
	{
		name = _Smoothness
		float = 0.9
	}
}

**Comment by shadowmage45** [comment]
Sounds good.  Will work on getting these added for the next release.  I was trying to keep the shader setups as simple as possible (for performance considerations)... but sometimes there is a thing as 'too simple'  (and I don't think there is much of a cost for shader uniforms).

**Comment by Electrocutor** [comment]
I expect that blending between maps costs a decent bit, but I can't imagine a single float multiplier should affect much.

**Comment by shadowmage45** [comment]
A MUL instruction is far cheaper than a texture-sample, bordering on 'free' on modern hardware.  About as cheap as an instruction gets.
