### ISSUE TITLE
Issue when no meshes or exludemeshes are set

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#13]
When neither a mesh nor exclude mesh are set, it will attempt to replace all visible meshrender material shaders with the one specified.

There needs to be a check against transparency though. The materials that were previously using a transparency-enabled shader (such as flag meshes) need to either have their own version of a PBR shader that supports transparency on the diffuse alpha or to just be skipped. I would recommend skipping as there are 3 transparency types and you probably don't want to have deal with all those variations.

**Comment by shadowmage45** [comment]
If you want to skip a mesh, use the exclude mesh feature.  That is precisely what it is for.

Yes, a shader that supports transparency needs to be added (or transparency support added to the existing ones).  But I'm not going to change the mesh/exclude mesh setup, as it works perfectly at the moment.

For the moment, you can **still** use the legacy stock transparent shaders on the parts.  You can even specify them in the configs for the texture replacements, as well as adjust their properties/etc.

If you would like assistance in figuring out the config setup for something like that, please let me know;  it is certainly possible to assign multiple different materials using the same patch/ KSP_MODEL_SHADER block.
