### ISSUE TITLE
Include some base common materials for use in cfgs

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#15]
Include a couple free license materials for use with your pbr shaders.

Examples:
https://www.assetstore.unity3d.com/en/#!/content/12949
https://www.assetstore.unity3d.com/en/#!/search/page=1/sortby=popularity/query=category:64

Suggestions:
- Aluminum (diff, norm, met)
- Aluminum Foil (normal)
- Aluminum Scratched (normal)
- Aluminum Dented (normal)
- Aluminum Painted (diff, norm, mask, met)
  - mask should be for paint, which can then have paint color changed via _MaskColor
- Gold
- Steel
- Steel Scratched
- Steel Rusted
- Carbon Fiber
- Kevlar
- Bigelow (Bigelow Aerospace Material)

**Comment by shadowmage45** [comment]
I have no intentions of distributing any assets with this mod.  It is intended as an API only, and any assets should be distributed with the mod that is using them.

(Why would this mod distribute assets, when it won't use them?  This mod, by itself, will do nothing)
