### ISSUE TITLE
Legacy shader support for older/incompatable systems.

### ISSUE THREAD

**Issue by T10a** [shadowmage45/TexturesUnlimited#16]
Due to Mesa providing only OpenGL 3.0 for systems around > 3 years old on Linux, this has resulted in TexturesUnlimited being nonfunctional in this mode and turning all reflective textures black.
This unfortunately may mean systems running OpenGl 3.0 need to revert from the TexturesUnlimited shader to classic Stock shaders to provide functionality.
It's a shame, because the new shader is really nice looking.

EDIT: Issue solved, but changed to a legacy reminder.

**Comment by Electrocutor** [comment]
Mesa added support for OpenGL 3.1 back in 2012...

**Comment by T10a** [comment]
Guess it might be my system then.
Here's glxinfo | grep "OpenGl version" output:
OpenGL version string: 3.0 Mesa 17.2.5

**Comment by shadowmage45** [comment]
Actually re-opening this one, to remind me to provide some sort of fallback for incompatible systems.

Sadly it will still mean using stock/legacy shaders, but it should allow for users to use mods that include TU without any additional workarounds.

**Comment by kaa253** [comment]
Actually I am not sure that OpenGL or Mesa are the real problem for all Linux setups. 
I also have the black textures in game and I get a lot of texture not founds in the Player.log.
Also the header of the log shows;
OpenGL:
    Version:  OpenGL 4.5 [4.5.0 NVIDIA 384.98]

[Player.log](https://github.com/shadowmage45/TexturesUnlimited/files/1526812/Player.log)

Minimal KSP_Linux 64 install of Versions
https://github.com/shadowmage45/TexturesUnlimited/releases/tag/1.0.0.5
https://github.com/shadowmage45/SSTULabs/releases/tag/0.7.39.147
https://github.com/shadowmage45/SSTULabs/releases/tag/PBR-0.1.0.5

**Comment by shadowmage45** [comment]
Interesting....

The 'texture-missing' messages are normal (because stock embeds texture names in the .mu models, and I have long since changed textures to something else).

However, if you have openGL > 3.5, it -should- work.  As far as I know it should be using the same shader variants that are built for OSX, and I know that those work just fine.

**Comment by shadowmage45** [comment]
Here is a good question that should help me answer where things are failing at --

Does SSTU work fine -without- the PBR expansion?  E.g. do the legacy SSTU recoloring shaders still work fine under Linux?

**Comment by T10a** [comment]
As found in the thread, adding -force-glcore to the launch options enables the shaders to work properly.
Will keep this thread open as a reminder for legacy system support for those with less capable PCs.

**Comment by shadowmage45** [comment]
Yeah, I have some ideas that might 'fix' the shader pack, but have been unable to find the time to make the changes so far.  Hopefully will get a testing shader pack put together in the next day or two.
