### ISSUE TITLE
Alpha Channel Inversion

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#24]
Enhancement Request
Please, add a keyword like 'ALBEDOALPHA_INVERT' to the 'SSTU/PBR/StockMetallicBumped' shader. It seems that some of the smoothness values that are used by default in stock parts are exactly reverse from what they should be while others seem to be correct.

**Comment by shadowmage45** [comment]
Interesting -- yeah, I had noticed that some of the stock parts had some oddities in them.  While I don't think this would be proper to add into the regular shaders, I have no problem with adding it to the 'stock replacement' shader variant(s).

Will see about getting it added in for the next release.

**Comment by shadowmage45** [comment]
````
            #if ALBEDOALPHA_INVERT
                color.a = 1 - color.a;
            #endif
````
