### ISSUE TITLE
TextureSet Names

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#25]
Please add a title property to TEXTURESET that is used in-game in the GUI switch right-click menu.

This would allow you to have for example Stock_Default, USI_Default, Porkjet_Default, Ven_Default as names with different settings; but visually the player would just see 'Default' as the name of all of them.

**Comment by shadowmage45** [comment]
Should already exist (at least the config portion of it):

https://github.com/shadowmage45/TexturesUnlimited/blob/master/Plugin/SSTUTools/KSPShaderTools/Util/TextureSet.cs#L13

Defaults to the 'name =' entry if no 'title =' is specified.

The title is used for display / GUI purposes only.

**Comment by Electrocutor** [comment]
My bad for missing it, sorry.

**Comment by shadowmage45** [comment]
No worries, I'm not the best at documenting things.
