### ISSUE TITLE
Additional Keywords and Albedo Color for Stock

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#26]
Since it seems to be somewhat quick and easy, could you add a couple more keywords to the stock shader?

ALBEDOALPHA_METAL
- denotes that metallicy should be read from alpha channel of albedo

ALBEDOALPHA_SMOOTH
- denotes that smoothness should be read from alpha channel of albedo

*current behavior is ALBEDOALPHA_SMOOTH, but this would allow any combination of inversion, metallicy, and smoothness from the alpha channel

----
This part will be confusing, so please try to bear with me. In basically everyone's parts whether they be stock or mods, everyone uses various shades of gray as the "metal" color. The attempt here would be specify what the metal color is and the further you get from it, the less smooth or metallic it becomes.

keyword: ALBEDO_METAL
keyword: ALBEDO_SMOOTH
color: _MetallicGlossColor

For the following example, we will assume an _MetallicGlossColor at (127,127,127)
Since we do not want black or white parts to be considered as metal (0,0,0) or (255,255,255); we will set the limits that are 0% to be within 64 RGB; so (63,63,63) and (191,191,191) are 0% in this case.

One minus the RGB difference ratio is what determines the %. In this case, the divisor would be 64+64+64=192. So if the albedo color was 63,127,127 that'd be (1 - (|64 - 127|/192 + |127-127|/192 + |127-127|/192)) = 67%.

Having a variance of 64 seems like a good place to start to me, but may need to be adjusted later depending on what the result would be.

How difficult do you think this would be?

---
The end result would be that most parts from stock and mods would be set as ALBEDOALPHA_SMOOTH and ALBEDO_METAL with an _MetallicGlossColor set at the shade of gray used for that group of parts.

**Comment by shadowmage45** [comment]
While I follow you on the first bits (reading metal from alpha channel, and/or reading smoothness from alpha, with keywords to swap between/combine behaviors), I'm more than a bit lost on what you are trying to accomplish from the rest of it.

Sounds like you are wanting to decompose the stock (or other mods') textures, at runtime, into 'metallic' and 'non-metallic' components, based on the color present in the albedo/diffuse texture and some sort of config/shader-parameter based cutoff range?   Is that about right?

(no clue on if it is doable, or how difficult, just trying to confirm what you are inquiring about)

**Comment by Electrocutor** [comment]
That about sums it up; but I'm also tossing things around in my head about also having the same ability for tinting. I am trying to think of a succinct and efficient way to accomplish it: even if the code is not especially readable.

If it was limited to 3 colors, it would basically be identical to your current Mask shader, except that it would not be forced only to red, green, and blue as the base colors.

Well, you understand the gist of it anyway. I imagine if you can come up with an efficient way to do it, then such a shader would be quite useful for more than just KSP.

This might also go back to the other conversation about hue shifting, just also including metal/smooth in the replacement algorithm. Nothing pressing at all, just would be exceptionally useful for applying to pre-existing mods.

There are effectively 12 colors that would need to be detected. Having 12 _Color's to be configured seems way too excessive to me though, so was trying to think of a good way to combine inputs and allow 3 outputs. When I reached this point I figured the difference between this and such specifying adhoc colors would be minimal. Anyway, just something to throw on the back-burner for simmer until you head hit your head on the toilet.
