### ISSUE TITLE
Efficiency - Use Shared Materials where applicable

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#27]
Use Shared Materials...

For each KSP_TEXTURE_SET, have it create shared materials instead of each being its own new instance.

They would need to switch from being a shared material to be an individual one if the Recolor GUI is clicked and any value is changed.

This will not make any difference in small craft; but makes a dramatic difference when having hundreds of the same part or parts that share the same material textures and properties.

**Comment by shadowmage45** [comment]
Any idea how to track all that from plugin code?  And keep it reasonably simple to maintain said code?

There is a reason I went with 'purely unique materials for everything' -- I don't have unlimited time to do development (nor am I getting paid for my time).

If you have some ideas that would work, while still being easy to implement and maintain, I'm all for it.

**Comment by Electrocutor** [comment]
my thought is that any texturesets made inside the part module config or shader replace config, you just keep the same. For ones that are specified as KSP_TEXTURE_SET you create them once then keep the materials in a static dictionary, then just look them up and set them as shared when processing the part loads or when doing texture switching.

In the code you execute for the GUI, just check if its using a shared material; if so, clone it and set as an instanced one. Maybe some day in the future you can actually check if you change a value while inside the GUI, but that isn't especially important right now.

It's not like this is critical or anything, but it does make a dramatic difference when you have hundreds of the same part. So if you don't want to mess with it, that's your prerogative, I just thought I'd mention it.

The stock game does not utilize this feature, even though it would benefit greatly from it (I had done a test a long while back).

**Comment by shadowmage45** [comment]
Indeed -- there could be fairly substantial RAM savings from not duplicating textures, especially if the same part/texture set was used in many parts in the scene.

> In the code you execute for the GUI, just check if its using a shared material;
This has been the problem I've encountered in the past -- how to check if it is using a shared or unique material?  As far as I know there is no Unity method to do so.  If you are aware of some method to do so (built in Unity method, or additional scripting), the rest should be fairly easy to implement.

**Comment by Electrocutor** [comment]
Renderer.material is where you set the instanced material
Renderer.sharedMaterial is where you set the shared material

You would need to destroy the .material after (or before?) setting a shared one so it would not continue to use resources.

**Comment by Electrocutor** [comment]
as far as Unity is concerned there is no difference between the two except that when the GameObject is destroyed, it also destroys the Renderer.material, but it does not destroy the Renderer.sharedMaterial.

**Comment by shadowmage45** [comment]
Yes.  But how to tell if a specific renderer is using the 'shared material' or a unique 'material'?

**Comment by Electrocutor** [comment]
just check if .material and/or .sharedMaterial is null.

**Comment by shadowmage45** [comment]
They are only null if they have never been assigned.

If a renderer has currently only ever used 'sharedMaterial' -- you can still use the 'material' property -- it will not return null, but it will in fact return a copy of whatever is in the sharedmaterial slot.

https://docs.unity3d.com/ScriptReference/Renderer-material.html
> If the material is used by any other renderers, this will clone the shared material and start using it from now on.

E.G. the first time you access the 'material' property, Unity internally copies the 'sharedMaterial', assigns it to the field, and returns the copied material.  'material' will never return null unless 'sharedMaterial' is also null.

----

Hmm... perhaps this might be able to handled in a bit more of a simple fashion (though it would require some differentiation in the code between the different texture assignment methods that I'm not fond of)
* Default Shader Assignments would always adjust the 'shared material'.
* TextureSwitch and RecoloringGUI would always adjust unique 'material'.
  * Ideally, some method would be found to track if these models are using the 'default' for that model, and only switch to unique materials if the user had adjusted away from the default.  Sadly, I'm not able to think of any method to do so without specifically tracking that additional data with every texture-switch/texture-set/part-module.

This should allow for shared materials to be used everywhere that they should (parts/models that do not adjust textures or materials in any way), while still giving unique materials to all of the parts/models that need them (that use the texture-switch and/or recoloring systems).

It would not be as efficient as a holistic approach... but it is something that I could actually implement in the near future without taking too much time, or adding too much additional complexity to the existing code.

**Comment by Electrocutor** [comment]
You could add a property to your TextureSet class: isShared. You would only set it to true if that TextureSet config was loaded from KSP_TEXTURE_SET. Then you could continue to use the shared textureset with TextureSwitch (as that will almost always be from KSP_TEXURE_SET definitions.

The only place you would ever need to check whether you are using a sharedMaterial or not is in the RecolorGUI.
