### ISSUE TITLE
Tinting / Recoloring Shader (Concept development)

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/TexturesUnlimited#30]
Create a specific shader intended solely for recoloring of existing stock/mod textures.

Current concept:
* Decompose current RGB into HSV
* Set H to value from recoloring GUI RGB selection
* S = ?
* V = ?

Unable to find a way to maintain color differential / minor hue differences.  Can replace hue entirely while keeping S+V.

S +V are more problematic.  You cannot simply set them to the value from the GUI, or the output will be a flat texture without any details.  Without an additional texture-input that says what the 'base' S+V are for any pixel, no manipulation of this data can be done without discarding the existing texture information.

**Comment by Aelfhe1m** [comment]
public static void ColorToHSV(Color color, out double hue, out double saturation, out double value)
    {
        int max = Math.Max(color.R, Math.Max(color.G, color.B));
        int min = Math.Min(color.R, Math.Min(color.G, color.B));
     
        hue = color.GetHue();
        saturation = (max == 0) ? 0 : 1d - (1d * min / max);
        value = max / 255d;
    }

HSL is easier if you can work with that instead:

    public static void ColorToHSL(Color color, out double hue, out double saturation, out double level)
    {
        hue = color.GetHue();
        saturation = color.GetSaturation();
        lightness = color.GetBrightness();
    }
