### ISSUE TITLE
[Enhancement] In-Flight Conditional Switching

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#41]
Add configurable options to KSPTextureSwitch that can automatically switch between TextureSets depending on conditions.

For example,
if (oVessel.geeForce > (oPart.gTolerance * 0.8))
{ SetTextureSet(glassCrack); }

**Comment by Electrocutor** [comment]
The type and number of conditions supported can just slowly accumulate over time.

Initially, I was thinking of the following cases:
- Part G limit versus Vessel current Gs
- Part temp limit versus Part current temp
- Part pressure limit versus Part current pressure

**Comment by shadowmage45** [comment]
Feel free to write up a PR.  I have no personally interest in that feature, and don't have the time to work on it.  

No problem if it were included (as long as it is entirely optional and doesn't interfere with existing uses)... but not something I'm going to spend time to write myself.
