### ISSUE TITLE
Stock Shader Bug

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#42]
To comply with how default KSP shaders work, if a texture does not have an alpha layer enabled, then the default specular is 0% instead of 100%. Personally, I think 30% or 40% would make more sense.

**Comment by shadowmage45** [comment]
I would think that the best setup would be to default to a value of 1.0 (100% gloss, 255 byte value), which would then allow for full control over the specular value through texture set configs.

(if the default value assigned to the 'empty texture' returned only 40%, that would be your max limit with no way to fix it through config)

But this is all moot -- there is no way to detect in the shader if a texture is assigned and use specific values (that would be something that would be enforced by the UnityEditor custom shader GUI).  From the shaders perspective, a texture is always assigned.  As these shaders aren't used through the Editor, there is no option for a custom GUI -- you just have to set up the configs properly to achieve your desired effect.

**Comment by Electrocutor** [comment]
If the diffuse doesn't have an alpha layer, then I just use the Metallic shader instead. The stock shader should work like the Squad stock shaders which have 0% specular if the diffuse does not have an alpha layer.

"But this is all moot -- there is no way to detect in the shader if a texture is assigned and use specific values"
If this is true, then why does Squad's shader do exactly that?

**Comment by shadowmage45** [comment]
> If this is true, then why does Squad's shader do exactly that?

It doesn't.  Squad has a special shader for parts with no specular value -- the KSP/Diffuse shader.

Stock has two shaders (with sub-variants for bumped/emissive)
* KSP/Diffuse  (and bumped/emissive variants) -- this one has no specular support.  It ignores alpha channel
* KSP/Specular (and bumped/emissive variants) -- this one has specular support.  Specular value taken from alpha channel of diffuse texture.

At no point will the 'KSP/Specular' shader default to 'specular = 0'.  It will always pull the specular from the alpha channel in the diffuse texture.

**Comment by Electrocutor** [comment]
I was going to say mk1-2pod uses KSP/Emissive/Bumped Specular; but it seems that it does indeed have an alpha channel, merely it set to solid 255; however in-game, this does not translate to any specular... this makes me think some KSP specular shaders are broken, some are 0 to 255 and some are 255 to 0.

I'm going to spit out a list of material texture+shader for parts to see if I can make rhyme or reason out of it.

**Comment by shadowmage45** [comment]
Interesting find.  Indeed -- sounds like that part should be very shiny, but I know that the in-game view is extremely flat (I don't think even the windows have proper specular on them on that part).

Hmm... pretty sure the KSP shader sources are all available in the PartTools distribution -- it will tell you exactly how the values are used for the stock shaders.

http://kerbalspaceprogram.com/files/PartTools_AssetBundles.zip

Here is the surface function used by the KSP/Emissive/BumpedSpecular shader (this is the entirety of the functional code in that shader, the rest is properties/setup/variable declarations):
````
#pragma surface surf BlinnPhong
void surf (Input IN, inout SurfaceOutput o)
{
    float4 color = tex2D(_MainTex,(IN.uv_MainTex)) * _BurnColor;
    float3 normal = UnpackNormal(tex2D(_BumpMap, IN.uv_BumpMap));

    half rim = 1.0 - saturate(dot (normalize(IN.viewDir), normal));

    float3 emission = (_RimColor.rgb * pow(rim, _RimFalloff)) * _RimColor.a;
    emission += _TemperatureColor.rgb * _TemperatureColor.a;
    emission += (tex2D(_Emissive, IN.uv_Emissive).rgb * _EmissiveColor.rgb) * _EmissiveColor.a;
    
    o.Albedo = color.rgb;
    o.Emission = emission;
    o.Gloss = color.a;
    o.Specular = _Shininess;
    o.Normal = normal;

    o.Emission *= _Opacity;
    o.Alpha = _Opacity;
}
````
Shows that the value used for 'gloss' is taken directly from the diffuse texture alpha channel, with zero conditionals or manipulation.

(the blinn-phong model uses the 'specular' term (_Shininess property) in a fashion known as 'hardness' by most other modeling/rendering setups;  the 'gloss' value determines how bright the reflection is, while the 'specular' value determines how widely distributed the reflected light is/reflection angle)
  
Please let me know what you find out though -- very curious as to how that stock part (the mk1-2 pod) is not extremely shiny.  

Are you sure that it is using the specular shader for the entire model, or is it using it for just the window meshes (and using the standard diffuse shader for the rest of the model)?

**Comment by Electrocutor** [comment]
result is that a bunch of command pods use KSP/Emissive/Bumped Specular.
mk1-2pod, mk1landercan, mk2inline, mk2standard, etc.

checking the textures for all of these, about half of them use a 0-255 specular, the other half use 255-0; even though they are using the same shader. Other 3rd party parts do the same, like Nertea's station pods even have some meshes using 255-0 and other meshes using 0-255 on the same part in different areas. Consider me confused.

**Comment by Electrocutor** [comment]
Okay... I'm going to chalk this up as Squad's shaders are fubar. There's so many shaders and each one uses the same properties in different ways and with different intensities for the same values. What's more some parts of them are broken while other parts are inverted as compared to another similar shader.

**Comment by shadowmage45** [comment]
Hmm... I'll try to do some investigation on the stock shaders myself to see if I can figure out what is going on.  (not a big fan of mysteries...)
