### ISSUE TITLE
[Enhancement Request] ShaderPropertyOffset and ShaderPropertyScale

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#49]
Add a ShaderPropertyOffset and ShaderPropertyScale to allow tiling changes to material textures.

PROPERTY {
name = (texture property name)
offset = 0.0, 0.0
}

PROPERTY {
name = (texture property name)
scale = 1.0, 1.0
}

This would use Material.SetTextureOffset and Material.SetTextureScale.

A practical scenario would be having one textureset that uses a full UVWrap normal map across an entire mesh with another textureset that uses a small tiling pattern for a generic material type.

**Comment by shadowmage45** [comment]
Sounds good, will try to get them added in for the next release.

**Comment by shadowmage45** [comment]
Implemented.  You can give it a test drive from the 'dev' branch.  If you do, grab the entire /GameData folder as there are a couple other config changes there (needed for transparency fixes).

````
//scales
PROPERTY
{
    //e.g. _MainTex
    name =NAME_OF_TEXTURE_SLOT
    scale = 1.0, 1.0
}
//or
textureScale = _MainTex, 1.0, 1.0

//offsets
PROPERTY
{
    //e.g. _MainTex
    name = NAME_OF_TEXTURE_SLOT
    name = _MainTex
    offset = 0, 0
}
//or
textureOffset =_MainTex, 0, 0
````

At some point in the future I'll likely change (or add alias support) for property blocks to each have a unique node name, such as PROPERTY_COLOR, PROPERTY_SCALE, etc.  It wasn't needed originally, but now as there are multiple properties that might share the same 'name=' line (texture, scale, and offset), it becomes more desirable for the purpose of clarity and ease of patching.

The 'shorthand' versions don't really have the same problem, though they present other difficulties for patching.
