### ISSUE TITLE
Texture Layering

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#5]
Please allow texture layering via cfg. It'd be great if you could also have settings for making the layering dynamic, for example adding a rust layer when a part reaches a certain age and is in atmo or what not.

In Unity, this can be done like so:

        private void AddTextureLayer(Renderer oRenderer)
        {
            Material[] oMaterials = new Material[oRenderer.materials.Length + 1];
            Material oNewMaterial = new Material(Shader.Find("Standard"));

            for (int i = 0; i < oRenderer.materials.Length; i++)
            { oMaterials[i] = oRenderer.materials[i]; }

            oMaterials[oRenderer.materials.Length] = oNewMaterial;
            oRenderer.materials = oMaterials;
        }

**Comment by shadowmage45** [comment]
I have not experimented at all with multi-material setups; would have to become more familiar with its use (both in practice, and in code) before I would be able to implement it.

I would not be implementing any aging functionality (that would have to come from whatever mod wants to implement it), but certainly the texture/shader/material support should be done on this end of things.
