### ISSUE TITLE
(partly) Invisible parts issue

### ISSUE THREAD

**Issue by Gordon-Dry** [shadowmage45/TexturesUnlimited#57]
With latest dev, Oct 20 and Oct 21 2018
KSP 1.4.5 64-bit
-force-glcore
Windows

I just quit KSP, set TU to dev again and launched it to get proper logs.
After posting this I will revert to rls again ;)

---

First I believed it was an issue of BDB, but it wasn't:
https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/477

First I only recognized that weird behaviour with bluedog_Atlas_AdapterFuelTank - but later I also recognized it with mesh-switchable mounts of BDB engines.

I loaded the vessel where I recognized it first into VAB, created that following screenshot and exited again:
https://i.imgur.com/Kbx5Y5w.png

Used configs (all together in .7z at the end of this post):

GameData\000_TexturesUnlimited\TexturesUnlimited_Stock.cfg
https://pastebin.com/mrM1MqBM

GameData\000_TexturesUnlimited\TU_PorkjetStock.cfg
https://pastebin.com/nKkxBuEy

GameData\TURD\TU_Extras\
GameData\TURD\TU_Standardised_Switching\
GameData\TURD\TU_Stock_Recolour\
(I removed all textures from the .7z at the end of this post, only the configs stay inside)

I also put the whole TU folder in as on my system while testing.

All together and logs and stuff:
https://www.dropbox.com/s/gbm92s2tdzjrbft/2018-10-21_1%20TU%20issue.7z?dl=1

**Comment by shadowmage45** [comment]
Thanks for posting the information requested -- should make it possible to properly investigate the issue, and will let you know what I find.
