### ISSUE TITLE
-force-d3d11 some VAB icons still blue-haze

### ISSUE THREAD

**Issue by Gordon-Dry** [shadowmage45/TexturesUnlimited#62]
See for example
https://i.imgur.com/K4SGcJU.png

**Comment by GER-Space** [comment]
this might be some items that do thier own texture (and worse Shader) switching. This can lead to that kind of effects.

**Comment by shadowmage45** [comment]
Yeah, not much I can do to about other mods using non-stock shaders.

However, if provided with a list of the shader names, I _might_ be able to still target them with the shader replacement patches.  Don't expect me to come up with this list on my own though -- I can only 'support' stock setups out of the box.
