### ISSUE TITLE
We need versions compiled for older versions!

### ISSUE THREAD

**Issue by Footsiefat** [shadowmage45/TexturesUnlimited#65]
For KSP 1.2.2, I tried using the oldest release that still had most of the features but it still didn't work, it told me to run it in opengl so I forced it but it crashed when the game tried to load.

My system is:
i7 8700k
GTX 1080ti
Samsung 970 pro 512gb

My final aim is to make ksp "AS" realistic as possible, I have found an old copy of E.T.O but it needs to be run with 1.2.2 but I need this amazing mod to be part of this!

**Comment by shadowmage45** [comment]
I will not be supporting older KSP versions or maintaining multiple releases.  

All of the source is available, and you are welcome to compile your own, though it will of course be unsupported.

**Comment by Footsiefat** [comment]
That would be a great idea, except I have not compiled a KSP mod before as I have never needed to. Would you be able to explain how to do it please? :D

**Comment by shadowmage45** [comment]
Its really far beyond the scope of this mod to explain how to do modding.  Your best bet would be start on the KSP forums as they have links for many modding subjects -- 
https://forum.kerbalspaceprogram.com/index.php?/topic/170231-useful-references-for-modding-all-the-old-stickies/
https://forum.kerbalspaceprogram.com/index.php?/topic/153765-getting-started-the-basics-of-writing-a-plug-in/

However, I would say that if you don't have any previous experience with programming... this isn't the best way to get started.  It is a long and steep learning curve just to get your first 'hello world' program to compile, and then quite a long road past that to get to a state where you could successfully modify and compile others' source code.

Beyond that -- you may still run into other issues when trying to port the mod to that old of a KSP version.  Notably, I'm not even sure that the KSP 1.2.x release used a version of Unity that supported PBR shaders.  (There are very good reasons why back-ports to older KSP versions are not done).

----

In reality your best bet would be to use modern KSP versions (1.7+), and use mods that are compatible with that KSP version.  Trying to continue using older versions of the game will only be problematic (with more problems the older the version is).

Is there a specific reason you can't use modern KSP?

**Comment by Footsiefat** [comment]
Yeah sorry, E.T.O is needed for the extremely high res RSS textures.
Most links got removed and the dev has stopped developing it but here is the one I downloaded it from:[https://github.com/ufindbatman/E.T-1.2.2/releases/tag/1.1](https://github.com/ufindbatman/E.T-1.2.2/releases/tag/1.1 )

**Comment by shadowmage45** [comment]
Ahh,, RSS, explains it all.  RO+RSS have been the largest pain in my rear regarding their lack of progress and not keeping up with KSP updates; every single request I get for 'older KSP version support' is always from someone using RO.  Nothing I can do about that though.

----

You might actually have an easier time if you were to attempt to port ETO to modern KSP versions.  It is likely just a very simple texture pack with some minor plugin code to insert the textures where needed.  I haven't personally looked at the code (if it even has any), and it might even be possible to simply use those textures in place of the existing RSS texture sets.

^^^ Is likely something you could bring up in the RO/RSS forum threads.  You will find users there far more familiar with the subject content than I am (I have never used either RO or RSS, and only know of them from the pain they cause me).

**Comment by Footsiefat** [comment]
I know for a fact I cannot just swap the textures out, ksp loads a max of 16k textures. This uses 4, 16k textures put together. The developer does not respond to contact now and most people wouldnt be familiar with how to get it working well.
