### ISSUE TITLE
TU - Memory Leaks

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/TexturesUnlimited#67]
As reported on forums:

>I've noticed that there is a memory leak in 1.3.6.20(1.4.7.21 appears to just be a recompile?). I did extensive testing in various scenes with and without this mod watching it with memgraph and resource manager. In the main menu, ksc, VAB, pad and in flight it also causes memory usage to increase at a steady rate forever until it eventually crashes when you change the scene again. It's not outputting anything to the log indicating that something is wrong with it.

**Comment by Gordon-Dry** [comment]
Could you also put the forum link here for quick finding?

Question (to the author of the forum post):
Does it happen on all types of rendering, or is it bound to -forced-d3d11 and/or -force-glcore and/or without launch parameter (aka. DirectX 9)?

**Comment by shadowmage45** [comment]
>Could you also put the forum link here for quick finding?
Was reported through a PM, so... not really.

**Comment by shadowmage45** [comment]
Should be fixed in the next update.  Have disabled the TU reflection updating methods, which were the main use of 'Update' type methods were memory leaks might occur.

There may still be on-scene-change issues due to Material updates.

**Comment by Gordon-Dry** [comment]
I would like to know if the latest dev build is strictly for KSP 1.7.2 or if there is a chance that it can also be used on KSP 1.6.1.
