### ISSUE TITLE
Realtime Light from _Emissive

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#7]
Please add an optional cfg setting per TEXTURE to enabled real-time light from emissions.

Material.globalIlluminationFlags = MaterialGlobalIlluminationFlags.RealtimeEmissive

**Comment by shadowmage45** [comment]
Does this actually work in KSP / forward rendering path? (and without the full GlobalIllumination support?)

**Comment by Electrocutor** [comment]
I've done a bunch of messing around and I know it works in KSP, but I'm not sure if you have to first turn on other parts of Unity inside KSP or if those are on by default.

My playing around had this chunk at the beginning; whether or not anything in here allowed them to work or if they just work by default, you would need to test.

        public static void SetSceneGraphics(Scene oScene)
        {
            LightmapSettings.lightmapsMode = LightmapsMode.CombinedDirectional;

            RenderSettings.defaultReflectionResolution = 512;
            RenderSettings.reflectionIntensity = 1.0f;
            RenderSettings.reflectionBounces = 3; // number of passes, 1- reflective objects are black
            RenderSettings.defaultReflectionMode = UnityEngine.Rendering.DefaultReflectionMode.Skybox;
            //RenderSettings.skybox =

            //RenderSettings.fog = true;
            //RenderSettings.fogColor = new Color(255f, 0.5f, 0.5f, 0.0f);
            //RenderSettings.fogDensity = 0.5f;
            //RenderSettings.fogMode = FogMode.Exponential;

            //RenderSettings.fogMode = FogMode.Linear;
            //RenderSettings.fogStartDistance = 0.0f;
            //RenderSettings.fogEndDistance = 300.0f;

            if (oScene.name != "editor")
            {
                RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
                RenderSettings.ambientIntensity = 0.0f;
                RenderSettings.ambientLight = Color.black;
                RenderSettings.ambientSkyColor = Color.black;
                RenderSettings.ambientEquatorColor = Color.black;
                RenderSettings.ambientGroundColor = Color.black;
            }
            //RenderSettings.ambientProbe = 

            //RenderSettings.haloStrength = 1.0f;
            //RenderSettings.flareStrength = 1.0f;
            //RenderSettings.flareFadeSpeed = 0.5f;
        }

        public static void SetUnityGraphics()
        {
            UnityEngine.Rendering.BuiltinShaderType oBuiltInShaderType;

            QualitySettings.anisotropicFiltering = AnisotropicFiltering.Enable;
            QualitySettings.realtimeReflectionProbes = true;

            oBuiltInShaderType = (UnityEngine.Rendering.BuiltinShaderType.DeferredReflections
                | UnityEngine.Rendering.BuiltinShaderType.DeferredShading
                | UnityEngine.Rendering.BuiltinShaderType.DepthNormals
                | UnityEngine.Rendering.BuiltinShaderType.LensFlare
                | UnityEngine.Rendering.BuiltinShaderType.LightHalo
                | UnityEngine.Rendering.BuiltinShaderType.MotionVectors
                | UnityEngine.Rendering.BuiltinShaderType.ScreenSpaceShadows
                | UnityEngine.Rendering.BuiltinShaderType.Sprite);

            UnityEngine.Rendering.GraphicsSettings.SetShaderMode(oBuiltInShaderType, UnityEngine.Rendering.BuiltinShaderMode.UseBuiltin);
        }

**Comment by shadowmage45** [comment]
Bit more info on the subject:
https://unity3d.com/learn/tutorials/topics/graphics/emissive-materials

**Comment by shadowmage45** [comment]
From reading up on the limitations of emissive-lighting -- this feature would be of no use for parts/craft/vessels in KSP.

>Emission will only be received by objects marked as ‘Static’ or “Lightmap Static’ from the Inspector. Similarly, emissive materials applied to non-static, or dynamic geometry such as characters will not contribute to scene lighting.

Which means that dynamic objects (craft/parts) will not contribute light to the environment lighting.  They also won't receive emissive based lighting from emissive objects already in the environment.

If they can't cast it, and can't receive it... I'm not sure of what use this feature would be?  (statics added by KK to cast glow on the terrain?)

**Comment by Electrocutor** [comment]
After some testing with my own dll, I cannot get real-time light emissions to work with your shader, but if I use Shader.Find("Standard"); they work just fine. Unfortunately, the Standard shader built into KSP lacks too many subshaders to be useful (it doesn't even have a bump sub shader).

**Comment by shadowmage45** [comment]
Hmm... possibly there is some shader #pragma or other directive tags that are needed to activate the feature.

Have you been able to get the light-emission emissives to work on **non-static** emitters and receivers using the Standard shader?  My tests in the editor resulted in zero functionality on non-static objects.

**Comment by shadowmage45** [comment]
The included Standard shader missing features is due to how Unity compiles shaders, and is precisely the reason why I don't use the 'keyword' feature.  Unity tries to 'help' and only include the shader variants that _it thinks_ you need, and I've not found any precise method to control which ones it actually compiles and includes (might be possible, and if it is, I can look into supporting the feature as it could make the management of the shader files a bit easier)

**Comment by Electrocutor** [comment]
Dropping a few tidbits of required data to track down what is needed for this:

Material.globalIlluminationFlags = MaterialGlobalIlluminationFlags.RealtimeEmissive

Material.EnableKeyword ("_EMISSION");
Material.SetColor("_Emission", Color.white);

DynamicGI.SetEmissive(renderer,Color.white);

... the question is whether the keywords are being read from the Standard shader or from the GI; if the latter, then this can be used with the SSTU custom shader; if the former, you have to code your own version of real-time light emission to make it work.

**Comment by shadowmage45** [comment]
The keyword bits that you are seeing are only applied to the material.  That shouldn't even be needed with the TU shaders, as they don't (yet) support keywords and features such as emissive are always enabled if present.

Now, setting of the 'Material.globalIlluminationFlags' is going to be problematic.  It is not a keyword, nor a property, and really doesn't belong anywhere in TU.  Same with the mucking about with DynamicGI stuff.  All of that would belong more properly in a separate mod geared towards toying with the Unity rendering settings.  (I'm really not here to fix KSPs crappy graphics coding and setup, only to get some previously unavailable shaders working in KSP)

I still haven't seen any evidence that this feature would even work on dynamic objects.  In fact, Unity's documentation states exactly the opposite (that dynamic objects such as craft can neither cast nor receive real-time emissive lighting).
