### ISSUE TITLE
KSP 1.7+ - Reflection Issues

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/TexturesUnlimited#70]
Few issues with reflections in the recent versions of KSP when using the stock reflection probe.

* No scatterer atmosphere in reflections (only stock atmo?)
* No reflection of skybox from orbit (no stars)

**Comment by maushacks** [comment]
@shadowmage45  I am not quite sure if this is the correct thread. But with only restock 0.1.4 and TU 1.5.8.23 installed and dx11 forced, the stayputnik does lose its reflective features. Without TU its okay. An unexpected interaction. 

![ksp_TU_restock](https://user-images.githubusercontent.com/51866804/62977132-7e5f9380-be1e-11e9-846f-98c9d4070b7f.jpg)

Log: https://gist.github.com/maushacks/a5c5bc5b80ea5aaa162fd1ffdb319b4a
