### ISSUE TITLE
Reflection Probe problems?

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/TexturesUnlimited#8]
From forum post: https://forum.kerbalspaceprogram.com/index.php?/topic/167450-131-textures-unlimited-pbr-shader-texture-and-model-api-11-11-17/&do=findComment&comment=3218459

````
KSP_MODEL_SHADER
{
	name = Mk1

	model = Squad/Parts/Command/mk1pod/model
	model = Squad/Parts/Command/mk1LanderCan/model
	model = Squad/Parts/Command/mk1Cockpits/CockpitStandard
	model = Squad/Parts/Command/mk1Cockpits/CockpitInline
	model = Squad/Parts/Command/mk1Cockpits/Cabin

	model = Squad/Parts/Structural/mk1Parts/StructuralHollow
	model = Squad/Parts/Structural/mk1Parts/Fuselage
	model = Squad/Parts/Structural/mk1Parts/IntakeFuselage
	model = Squad/Parts/Structural/mk1Parts/Nacelle1
	model = Squad/Parts/Structural/mk1Parts/Nacelle2

	model = Squad/Parts/Aero/cones/NCS
	model = Squad/Parts/Aero/airIntakeRadialXM-G50/RadialIntake
	model = Squad/Parts/Aero/circularIntake/CircularIntake
	model = Squad/Parts/Aero/circularIntake/ConeIntake
	model = Squad/Parts/Aero/ramAirIntake/RampIntake

	model = Squad/Parts/Engine/jetEngines/turboFanSize1
	model = Squad/Parts/Engine/jetEngines/turboJet
	model = Squad/Parts/Engine/jetEngines/turboRamJet

	model = Squad/Parts/Utility/dockingPortInline/model

	TEXTURE
	{
		shader = SSTU/PBR/StockMetallicBumped

		mesh = obj_base
		mesh = Cockpit
		mesh = Cabin

		mesh = StructuralHollow
		mesh = Fuselage
		mesh = IntakeFuselage
		mesh = Nacelle1
		mesh = Nacelle2

		mesh = Cone
		mesh = RadialIntake
		mesh = FanIntake
		mesh = ConeIntake
		mesh = RampIntake

		mesh = TurboFanSize1
		mesh = Reverser
		mesh = TurboJet
		mesh = TurboRamjet

		mesh = housing
		mesh = door1
		mesh = door2
		mesh = port

		mesh = window

		mesh = rung
	}
}
````
 

Build any craft out of Mk1 parts.
Time-warp to a bit past morning.
Roll around slowly and watch the lighting across the whole vessel as well as the brightness of reflections.

**Comment by shadowmage45** [comment]
Erm... why am I wasting my time submitting issues for other people that I have not seen and cannot confirm?

If you really want this looked at, open an issue on it yourself.  Include all of the information that I asked for (craft file, patches, any other textures or files needed).

**Comment by Temeter** [comment]
Hm, I tried it and didn't yet see any issue.

**Comment by shadowmage45** [comment]
Yep... which is why I closed the ticket.  I have not personally seen the problem, and the person reporting the problem did not want to include the information needed for me to debug it, nor open an issue ticket with said information as would have been the proper course of action.

So... I'm not going to worry about it any further (until/unless all of the information needed to duplicate the problem is given).

**Comment by Electrocutor** [comment]
Okay... after an enormous of testing I've figured out what is causing it. The light level of the reflection is being taken 100% of from the terrain texture, completely ignoring all light. This applies to all sides, including the top that is not even reflecting any of the terrain.

**Comment by shadowmage45** [comment]
From those images it looks like it is not capturing the terrain + atmosphere, or possibly just the terrain?  Either way, looks like it is dropping a couple of the layers that it should be rendering.

Does this happen often for you?  And is it transient/temporary, or does it persist for the length of the flight?  Does it happen with the PBR/Metallic shader as well?
(just trying to figure out why I have never seen the problem; there should not be any real difference between the PBR/Metallic and the stock-replacement one)

**Comment by Electrocutor** [comment]
I haven't used the PBR/Metallic much, as it requires me to create a texture for each part. It happens 100% of the time and is completely stable now that I tracked it down. a good place to see it is slowly rolling on the launch platform because the platform grate is black and the concrete around it is almost white, so the second you roll off the grate, the whole craft lights up. Also, the effect is persistent for any duration of time.

**Comment by shadowmage45** [comment]
Thanks for the info, that gives me a few ideas on what might be going on and where to start investigating.

**Comment by Electrocutor** [comment]
SSTU/PBR/Metallic does not demonstrate the same behavior. I have only seen it so far in SSTU/PBR/StockMetallicBumped; but have not tested the others.

**Comment by shadowmage45** [comment]
Very interesting that I've not seen this problem in my testing then, as I've been using the SSTU/PBR/Metallic shader all over the place.

Hmm... could it possibly be related to the position of the reflection probe in relation to the scenery itself?  Most of my tests have been with vessels that are elevated above the ground by at least a few meters (large wheels, launch clamps), and often the root part is at the top of a rocket (reflection probes currently located at Vessel.transform, which is located at the root parts models' origin).

(Suppose I'm just going to have to try to use your patched stock-CM pod to do testing; if I can't duplicate the problem using the exact same parts/shaders/textures......)

As I'll be doing a bit of other testing tonight, I'll see about taking some time to do testing to try and replicate this problem.

**Comment by Temeter** [comment]
I wonder if this is connected with a problem i faced? I had that giant, circular mirror-ball, but when I launched another craft, that ball had multiple transparent reflections overlaying each others. Mb there is some issue with reinitializing the stuff.

Didn't mention it because I hadn't yet reproduced it (used higher update/resolution rate).

**Comment by shadowmage45** [comment]
What you are describing sounds like the 'blended probes' functionality (blends the image between to nearby reflection probes), and is an intentional feature of the Unity reflection setup.  It can be disabled (and might end up doing so).

I have some thoughts as to what is causing this -- there are some non-visible meshes that are placed on the launchpad and runway, something used by some of the FX stuff.  These have caused problems with KSPWheel raycasts in the past, and I'm betting that the reflection camera is picking up and rendering the insides of these (normally invisible) meshes.  Would also explain why I haven't seen it in my tests -- the reflection probe is located higher on my test vessels, so never intersects with the invisible meshes.

**Comment by Temeter** [comment]
Hm, my probe was pretty high. Not a great shot, but the only screenshot I've made of the broken thing:

https://i.imgur.com/kbngJwt.jpg

**Comment by shadowmage45** [comment]
@Temeter What you are seeing is normal; that is the blending of the reflection probes.  Yes, it results in some doubled images, but it is part of the Unity implementation.

Have been able to confirm/duplicate the problem as reported by @Electrocutor though, using the stock-replacement patch on one of the stock rover craft files.

It appears as if it is losing the skybox rendering.  The rest of the scenery still renders, but the atmopshere in particular disappears, which leaves ~1/2 of the environment map as being black.

**Comment by shadowmage45** [comment]
Since I've finally been able to replicate the problem, I'm going to take some time over the upcoming holiday to see if I can track down exactly what/why/where/how (and why it doesn't seem to effect the SSTU parts/shaders).

Couple things to investigate:
* The skybox is obviously still visible -in KSP-, so its not like its going somewhere.
  * Or is it?  This could be related to the KrakenBane dynamic-origin stuff.
  * Exactly -where- is the skybox (or rather the atmosphere-sphere) located in world-space?  What are its dimensions?  (this will help set up the camera culling/frustum properly)
  * Is they atmosphere updated when krakensbane shifts the origin?
* Could it be that the galaxy box is getting rendered in front of the atmosphere?  (when in-atmo, and the sun is visible, the galaxy-box is dynamically darkened to appear black)
* So the main to possibilities are either
  * Floating-point-origin discrepancies
  * Inconsistent rendering of layers.

**Comment by shadowmage45** [comment]
This is definitely not limited to the stock-replacement shader, and is an underlying problem with the positioning of the camera while rendering the 'atmosphere' layer.

While doing some play/testing, I noticed in the reflection in one of the stock parachutes that the atmosphere was a small sphere being rendered somewhere above the parachute.

![screenshot110](https://user-images.githubusercontent.com/1503399/33159808-eb8b6b68-cfd3-11e7-8979-cbc742ad824c.png)

The reason it was never encountered before is because Scatterer was always installed for testing, which does not suffer the same atmosphere positioning problems.

Will need to find what game-object the stock atmosphere is attached to, and position/rotate the camera appropriately to capture it during reflection texture updates.

**Comment by shadowmage45** [comment]
Looks like the stock atmosphere is actually done in scaled space, and normally captured with the scaled-space camera.  I have adjusted the camera setups to hopefully fully mimic the stock setup.

So far after ~30 mins of flying and driving around the KSC I have not had any issues.  Previously it would pop up very regularly.

Re-installing scatterer/eve/etc to make sure I haven't broken anything there....

**Comment by shadowmage45** [comment]
So far so good on scatterer/eve from in-atmo....
(yes, that is a giant reflective sphere that I added for debugging....)
![screenshot38](https://user-images.githubusercontent.com/1503399/33222948-8efcbe38-d118-11e7-9df3-e7bab63c791d.png)

And in orbit....

![screenshot39](https://user-images.githubusercontent.com/1503399/33222981-d4004c7a-d118-11e7-889a-ce3509154ea6.png)


Going to call this one solved.
