### ISSUE TITLE
TexturesUnlimited parts have no models

### ISSUE THREAD

**Issue by PlasticGuy131** [shadowmage45/TexturesUnlimited#80]
I am using ROTanks for realism overhaul in KSP 1.6 and ROTanks parts have no models.

This issue can be avoided by using the latest TU version for KSP 1.7, however tanks have no texture change options. This may be a problem with ROTanks.

**Comment by Gordon-Dry** [comment]
See
https://github.com/KSP-RO/ROTanks/pull/3
