### ISSUE TITLE
NRE From TexturesUnlimitedDebug

### ISSUE THREAD

**Issue by marr75** [shadowmage45/TexturesUnlimited#81]
TexturesUnlimitedDebug.Awake will (as far as I can tell) always throw an NRE if TUGameSettings.Debug is false. Your code comment is that you're removing the button because you know it's not null but debug isn't true and that just isn't so.

Your conditionals are `debugAppButton == null && debug` and `debugAppButton != null && debug`, ultimately, in the most common case where debug is always false, you're just testing the value of debug so your assumption that the button isn't null is false.

Seems simpler to keep away from that bug by doing:
```csharp
if (debug) {
    if (debugAppButton == null) {
        tex = GameDatabase.Instance.GetTexture("Squad/PartList/SimpleIcons/RDIcon_fuelSystems-highPerformance", false);
        debugAppButton = ApplicationLauncher.Instance.AddModApplication(
            debugGuiEnable, debugGuiDisable, null, null, null, null,
            ApplicationLauncher.AppScenes.FLIGHT | ApplicationLauncher.AppScenes.SPH | ApplicationLauncher.AppScenes.VAB, tex
        );
    }
    else {
        // reset callback refs to the ones from THIS instance of the KSPAddon (old refs were stale, pointing to methods for a deleted class instance)
        debugAppButton.onTrue = debugGuiEnable;
        debugAppButton.onFalse = debugGuiDisable;
    }
}
else if (debugAppButton != null) {
    ApplicationLauncher.Instance.RemoveModApplication(debugAppButton);
}
```

I've remedied it in my local copy of TU using dnSpy and I've got too many forks and PRs floating around the KSP world right now but here's the issue and that code will fix it.

**Comment by shadowmage45** [comment]
Thanks for spotting it and providing a potential solution.

I should maybe test my releases in non debug mode once in awhile, eh?   :)
